from typing import Annotated, Any
from typing_extensions import TypedDict
from langgraph.graph import MessagesState

from luna_workstation.domain import AgentOpinion


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[
        str, "Company or asset that we are interested in trading"
    ]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    market_opinion: Annotated[
        AgentOpinion | dict[str, Any] | None, "Structured Market Analyst opinion"
    ]
    sentiment_opinion: Annotated[
        AgentOpinion | dict[str, Any] | None,
        "Structured Social Media Analyst opinion",
    ]
    news_opinion: Annotated[
        AgentOpinion | dict[str, Any] | None, "Structured News Analyst opinion"
    ]
    fundamentals_opinion: Annotated[
        AgentOpinion | dict[str, Any] | None, "Structured Onchain Analyst opinion"
    ]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[
        str, "Setup proposal generated by the Setup Planner"
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    final_trade_summary_json: Annotated[
        str, "Validated-source JSON summary emitted by the Portfolio Manager"
    ]
    past_context: Annotated[
        str,
        "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)",
    ]
    quant_signal: Annotated[
        str, "Pre-computed quantitative signal (prompt block from SignalEngine)"
    ]
    market_context: Annotated[
        str, "Pre-computed market microstructure and cross-venue context"
    ]
    news_context: Annotated[
        str, "Pre-computed source-grounded news catalyst context"
    ]
    news_context_snapshot: Annotated[
        dict[str, Any], "Normalized NewsContext snapshot for provenance"
    ]
    scenario_plan: Annotated[
        str, "LLM-generated scenario plan (markdown from Scenario Planner)"
    ]
    scenario_plan_json: Annotated[
        str, "LLM-generated scenario plan (JSON from Scenario Planner)"
    ]
